export const myNotes = [
    {
        name:"notes", 
        value:"notes",
        id:"note0"
    },
    {
        name:"notes",
        value:"notes",
        id:"note1"
    },
    {
        name:"notes",
        value:"notes",
        id:"note2"
    },
    {
        name:"notes",
        value:"notes",
        id:"note3"
    },
    {
        name:"notes",
        value:"notes", 
        id:"note4"       
    }
];